version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: python
        auth:
          username: davidperelroizen
          password: Davidou2410$
    steps:
      - checkout
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            python3 -m venv venv
            pip install -r requirements.txt
      - run:
          name: Pytest launch
          command: |
            mkdir test-results
            pytest
      - store_test_results:
          path: test-results
      - run:
          name: Flake 8
          command: flake8

  heroku_deploy:
    docker:
      - image: python
        auth:
          username: davidperelroizen
          password: Davidou2410$
    steps:
      - heroku/deploy-via-git:
          force: true

workflows:
  on_commit:
    jobs:
      - build_and_test
      - heroku_deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
