version: 2.1
jobs:
  build_and_test:
    docker:
      - image: python
        auth:
          username: davidperelroizen
          password: Davidou2410$

    steps:
      - checkout
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            python3 -m venv venv
            ./venv/Scripts/Activate.ps1
            pip install -r requirements.txt
      - run:
          name: Pytest launch
          command: python pytest
      - store_test_results:
          path: test-results

workflows:
  on_commit:
    jobs:
      - build_and_test