version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.6.2
        auth:
          username: davidperelroizen
          password: Davidou2410$

    steps:
      - checkout
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            python3 -m venv venv
            .\venv\Scripts\Activate.ps1
            pip install -r requirements.txt
      - run:
          name: Pytest launch
          command: |
            .\venv\Scripts\Activate.ps1
            pytest
